### ISSUE TITLE
Not able to run it

### ISSUE THREAD

**Issue by pranavvd22** [LetPeopleWork/AzureDevOpsFlowScripts#5]
I tried running the python file, but I am getting error
Can you please help

**Comment by huserben** [comment]
Hi @pranavvd22 

Note: I removed your image because your token was visible. Ideally, in future you paste the text as string and remove sensitive information to not expose your org to any risks.

From what I saw in your image, you have not specified the team project, so the script fails. You have to specify this using the "--TeamProject" argument. If this is omitted, the script will fail.

You can see an example [in the ReadMe](https://github.com/LetPeopleWork/AzureDevOpsFlowScripts#calculate-work-item-age).

Please let me know if that solved your problem.

**Comment by huserben** [comment]
Closed due to inactivity
